- name: Install NFS client packages
  yum:
    name:
      - nfs-utils
    state: present

- name: Deploy systemd mount unit file for NFS
  template:
    src: nfs-mount.j2
    dest: "/etc/systemd/system/{{ nfs_mount | regex_replace('/', '-') }}.mount"

- name: Deploy systemd automount unit file for NFS
  template:
    src: nfs-automount.j2
    dest: "/etc/systemd/system/{{ nfs_mount | regex_replace('/', '-') }}.automount"
  notify:
    - reload systemd
    - enable nfs automount


